In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

import pandas as pd

cc = np.concatenate

FPS = 30.03
DT = 1/FPS

In [2]:
df_behav = pd.read_csv('data/simple/c_song_f_behav.csv')
cols = df_behav.columns

In [3]:
# split big df into dfs for individual trials
ntr = np.max(df_behav.ID) + 1
df_tr_0 = [df_behav[df_behav.ID == i] for i in range(1)][0]
df_behav = None

In [4]:
t = np.arange(0, 370, DT)
i = ((10 <= t)&(t < 70))

In [5]:
# sine block trial (10 sec Q, 60 sec S, 300 sec P)
df_s = pd.DataFrame(columns=cols)
df_s['T'] = t
df_s['ID'] = 0
df_s['FRAME'] = np.arange(len(t))
df_s['Q'] = (~i).astype(int)
df_s['S'] = i.astype(int)
df_s['P'] = 0
df_s['F'] = 0

for kbhv in ['FFV', 'FFA', 'FLS', 'FRS', 'FMFV', 'FMLS']:
    df_s[kbhv] = np.random.randn(len(t))
    
# pulse block trial (10 sec Q, 60 sec S, 300 sec P)
df_p = pd.DataFrame(columns=cols)
df_p['T'] = t
df_p['ID'] = 1
df_p['FRAME'] = np.arange(len(t))
df_p['Q'] = (~i).astype(int)
df_p['P'] = i.astype(int)
df_p['S'] = 0
df_p['F'] = 0

for kbhv in ['FFV', 'FFA', 'FLS', 'FRS', 'FMFV', 'FMLS']:
    df_p[kbhv] = np.random.randn(len(t))

In [6]:
df_cc = pd.concat([df_s, df_p], ignore_index=True)

In [7]:
df_cc

,ID,FRAME,T,Q,S,P,F,FFV,FFA,FLS,FRS,FMFV,FMLS
0,0,0,0.00000,1,0,0,0,0.532378,-0.179481,0.425027,2.170994,1.215847,0.557477
1,0,1,0.03330,1,0,0,0,-1.713278,-0.712379,-0.317208,0.287841,0.664766,-0.019462
2,0,2,0.06660,1,0,0,0,-0.005653,-0.289923,-0.238194,0.628474,1.171294,0.455047
3,0,3,0.09990,1,0,0,0,-0.855684,-0.736243,-0.836451,-0.055651,-1.008228,0.358599
4,0,4,0.13320,1,0,0,0,1.693326,-0.593708,-0.906913,0.354482,0.224031,0.689262
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22219,1,11107,369.86347,1,0,0,0,-0.504757,0.451136,1.775186,1.194011,-0.224407,0.656095
22220,1,11108,369.89677,1,0,0,0,-1.761324,-0.340205,-0.048488,0.760350,-0.298026,1.329152
22221,1,11109,369.93007,1,0,0,0,-0.061890,0.616118,-1.057193,-1.010955,1.262468,-1.109192
22222,1,11110,369.96337,1,0,0,0,-0.765122,-1.896638,-0.019359,-0.755177,0.230285,-1.227346
22223,1,11111,369.99667,1,0,0,0,0.533306,-0.554074,-0.666414,-0.460151,-0.234683,0.252312

In [8]:
df_cc.to_csv('data/simple/block_song_f_behav.csv', index=False)

In [9]:
pd.read_csv('data/simple/block_song_f_behav.csv')

,ID,FRAME,T,Q,S,P,F,FFV,FFA,FLS,FRS,FMFV,FMLS
0,0,0,0.00000,1,0,0,0,0.532378,-0.179481,0.425027,2.170994,1.215847,0.557477
1,0,1,0.03330,1,0,0,0,-1.713278,-0.712379,-0.317208,0.287841,0.664766,-0.019462
2,0,2,0.06660,1,0,0,0,-0.005653,-0.289923,-0.238194,0.628474,1.171294,0.455047
3,0,3,0.09990,1,0,0,0,-0.855684,-0.736243,-0.836451,-0.055651,-1.008228,0.358599
4,0,4,0.13320,1,0,0,0,1.693326,-0.593708,-0.906913,0.354482,0.224031,0.689262
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22219,1,11107,369.86347,1,0,0,0,-0.504757,0.451136,1.775186,1.194011,-0.224407,0.656095
22220,1,11108,369.89677,1,0,0,0,-1.761324,-0.340205,-0.048488,0.760350,-0.298026,1.329152
22221,1,11109,369.93007,1,0,0,0,-0.061890,0.616118,-1.057193,-1.010955,1.262468,-1.109192
22222,1,11110,369.96337,1,0,0,0,-0.765122,-1.896638,-0.019359,-0.755177,0.230285,-1.227346
22223,1,11111,369.99667,1,0,0,0,0.533306,-0.554074,-0.666414,-0.460151,-0.234683,0.252312