Create surrogate neural population responses during natural behavior trials using variations on multiplicative adaptation neural models of Baker et al data.

In [1]:
%matplotlib inline
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
from scipy import signal, stats
from sklearn import linear_model
import sys
import warnings; warnings.filterwarnings("ignore")

from aux import get_seg
from disp import set_font_size
from my_stats import nanpearsonr

from record import smlt_ppln_ma

cc = np.concatenate

FPS = 30.03  # sampling rate of behavioral data
DT = 1/FPS

Load behavioral data from Coen et al 2014

In [2]:
df_behav = pd.read_csv('data/simple/c_song_f_behav.csv')
df_behav

,ID,FRAME,T,Q,S,P,F,FFV,FFA,FLS,FRS,FMFV,FMLS
0,0,0,0.000000,1,0,0,0,0.231,0.0000,0.159,0.077,-0.058526,0.274257
1,0,1,0.033300,1,0,0,0,0.314,0.0385,0.025,0.044,0.100623,0.298490
2,0,2,0.066600,1,0,0,0,0.308,0.0025,0.029,0.011,0.147629,0.271865
3,0,3,0.099900,1,0,0,0,0.319,0.0020,0.016,0.016,0.091174,0.306112
4,0,4,0.133200,1,0,0,0,0.312,-0.0315,0.030,0.002,0.065871,0.306439
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4978565,275,27100,902.430902,1,0,0,0,0.217,0.0280,0.029,0.058,-0.171418,0.136184
4978566,275,27101,902.464202,1,0,0,0,0.210,-0.1045,0.138,0.322,0.032522,0.249171
4978567,275,27102,902.497502,1,0,0,0,0.008,-0.0910,0.034,0.260,0.033202,0.010844
4978568,275,27103,902.530803,1,0,0,0,0.028,0.0695,0.010,0.090,0.012059,0.027177
4978569,275,27104,902.564103,1,0,0,0,0.147,0.0000,0.065,0.001,0.089547,0.133474

In [3]:
# split big df into dfs for individual trials
n_tr = np.max(df_behav.ID) + 1
dfs_tr = [df_behav[df_behav.ID == i] for i in range(n_tr)]

tr_lens = np.array([len(df_tr) for df_tr in dfs_tr])
tr_lens_cum = cc([[0], np.cumsum(tr_lens)])

n_t_total = np.sum(tr_lens)
assert n_t_total == tr_lens_cum[-1]
df_behav = None

# Baseline MA model params

In [4]:
# neural response fits from Baker data
df_ma_param = pd.read_csv('data/simple/neur/baker_ma_fit_param.csv')
df_ma_param

,EXPT_ID,LINE,FLY,ROI,ROI_USED,FIT_ERR,SUCCESS,T_0,R_0,TAU_R,TAU_A,X_S,X_P
0,0,R70G01,0,somas,False,0.275200,True,-0.000000,0.028882,6.202615,30.336758,-4.958290,-2.597432
1,1,R70G01,1,somas,False,0.186212,True,0.117647,0.025128,3.835468,21.821295,-4.163967,-1.472075
2,2,R70G01,2,somas,False,0.248414,True,-0.000000,0.055962,6.017162,15.058055,-6.248007,-2.095952
3,3,R70G01,3,somas,False,0.455963,True,-0.000000,-0.014227,6.016828,11.820576,-5.679735,-2.118245
4,4,R70G01,4,somas,False,0.229018,True,-0.000000,0.019831,6.434825,55.496220,-4.415761,-2.863647
...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,219,VT34811,0,somas,False,0.276087,True,-0.000000,0.039119,1.799608,1440.994269,-0.049828,2.494657
220,220,VT34811,0,ascending projection,False,0.037801,True,-0.000000,-0.001886,1.298841,27.643238,0.098451,2.457383
221,221,vPN1_split,0,somas,False,0.404112,True,-0.588235,-0.014702,4.151226,6.155551,8.332263,2.353217
222,222,vPN1_split,1,somas,False,1.205977,True,0.235294,-0.095665,5.924070,90.705238,2.390705,0.604586
223,223,vPN1_split,2,somas,False,0.096240,True,-0.000000,-0.000413,3.664384,10.471628,6.416873,1.021095

# Depolarizing responses only

In [6]:
SAVE_DIR_MA = 'data/simple/mlv/ma_alt/baker_ma_dep_only'
SAVE_PFX_MA = 'mlv_baker_ma_dep_only'

if not os.path.exists(SAVE_DIR_MA):
    os.makedirs(SAVE_DIR_MA)

# neural response fits from Baker data
df_ma_param = pd.read_csv('data/simple/neur/baker_ma_fit_param.csv')
df_ma_param['X_S'][df_ma_param['X_S'] < 0] = 0
df_ma_param['X_P'][df_ma_param['X_P'] < 0] = 0

df_ma_param

,EXPT_ID,LINE,FLY,ROI,ROI_USED,FIT_ERR,SUCCESS,T_0,R_0,TAU_R,TAU_A,X_S,X_P
0,0,R70G01,0,somas,False,0.275200,True,-0.000000,0.028882,6.202615,30.336758,0.000000,0.000000
1,1,R70G01,1,somas,False,0.186212,True,0.117647,0.025128,3.835468,21.821295,0.000000,0.000000
2,2,R70G01,2,somas,False,0.248414,True,-0.000000,0.055962,6.017162,15.058055,0.000000,0.000000
3,3,R70G01,3,somas,False,0.455963,True,-0.000000,-0.014227,6.016828,11.820576,0.000000,0.000000
4,4,R70G01,4,somas,False,0.229018,True,-0.000000,0.019831,6.434825,55.496220,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,219,VT34811,0,somas,False,0.276087,True,-0.000000,0.039119,1.799608,1440.994269,0.000000,2.494657
220,220,VT34811,0,ascending projection,False,0.037801,True,-0.000000,-0.001886,1.298841,27.643238,0.098451,2.457383
221,221,vPN1_split,0,somas,False,0.404112,True,-0.588235,-0.014702,4.151226,6.155551,8.332263,2.353217
222,222,vPN1_split,1,somas,False,1.205977,True,0.235294,-0.095665,5.924070,90.705238,2.390705,0.604586
223,223,vPN1_split,2,somas,False,0.096240,True,-0.000000,-0.000413,3.664384,10.471628,6.416873,1.021095

In [7]:
expt_ids = df_ma_param['EXPT_ID']

# get parameters
tau_rs = np.array(df_ma_param['TAU_R'])
tau_as = np.array(df_ma_param['TAU_A'])
x_ss = np.array(df_ma_param['X_S'])
x_ps = np.array(df_ma_param['X_P'])

In [8]:
# compute surrogate linear neural responses for each trial
for ctr, df_tr in enumerate(dfs_tr):
    df_tr_nrl_ma = df_tr.copy()
    sys.stdout.write('.')
    
    i_s = np.array(df_tr['S']).astype(float)
    i_p = np.array(df_tr['P'] | df_tr['F']).astype(float)
    
    # simulate ppln response
    rs = smlt_ppln_ma(i_s, i_p, tau_rs, tau_as, x_ss, x_ps, DT)
        
    df_tr_nrl_ma[[f'R_{expt_id}' for expt_id in expt_ids]] = rs
        
    np.save(os.path.join(SAVE_DIR_MA, f'{SAVE_PFX_MA}_tr_{ctr}.npy'), np.array([{'df': df_tr_nrl_ma}]))

....................................................................................................................................................................................................................................................................................

# Hyperpolarizing responses only

In [6]:
SAVE_DIR_MA = 'data/simple/mlv/ma_alt/baker_ma_hyp_only'
SAVE_PFX_MA = 'mlv_baker_ma_hyp_only'

if not os.path.exists(SAVE_DIR_MA):
    os.makedirs(SAVE_DIR_MA)

# neural response fits from Baker data
df_ma_param = pd.read_csv('data/simple/neur/baker_ma_fit_param.csv')
df_ma_param['X_S'][df_ma_param['X_S'] > 0] = 0
df_ma_param['X_P'][df_ma_param['X_P'] > 0] = 0

df_ma_param

,EXPT_ID,LINE,FLY,ROI,ROI_USED,FIT_ERR,SUCCESS,T_0,R_0,TAU_R,TAU_A,X_S,X_P
0,0,R70G01,0,somas,False,0.275200,True,-0.000000,0.028882,6.202615,30.336758,0.000000,0.000000
1,1,R70G01,1,somas,False,0.186212,True,0.117647,0.025128,3.835468,21.821295,0.000000,0.000000
2,2,R70G01,2,somas,False,0.248414,True,-0.000000,0.055962,6.017162,15.058055,0.000000,0.000000
3,3,R70G01,3,somas,False,0.455963,True,-0.000000,-0.014227,6.016828,11.820576,0.000000,0.000000
4,4,R70G01,4,somas,False,0.229018,True,-0.000000,0.019831,6.434825,55.496220,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,219,VT34811,0,somas,False,0.276087,True,-0.000000,0.039119,1.799608,1440.994269,0.000000,2.494657
220,220,VT34811,0,ascending projection,False,0.037801,True,-0.000000,-0.001886,1.298841,27.643238,0.098451,2.457383
221,221,vPN1_split,0,somas,False,0.404112,True,-0.588235,-0.014702,4.151226,6.155551,8.332263,2.353217
222,222,vPN1_split,1,somas,False,1.205977,True,0.235294,-0.095665,5.924070,90.705238,2.390705,0.604586
223,223,vPN1_split,2,somas,False,0.096240,True,-0.000000,-0.000413,3.664384,10.471628,6.416873,1.021095

In [7]:
expt_ids = df_ma_param['EXPT_ID']

# get parameters
tau_rs = np.array(df_ma_param['TAU_R'])
tau_as = np.array(df_ma_param['TAU_A'])
x_ss = np.array(df_ma_param['X_S'])
x_ps = np.array(df_ma_param['X_P'])

In [8]:
# compute surrogate linear neural responses for each trial
for ctr, df_tr in enumerate(dfs_tr):
    df_tr_nrl_ma = df_tr.copy()
    sys.stdout.write('.')
    
    i_s = np.array(df_tr['S']).astype(float)
    i_p = np.array(df_tr['P'] | df_tr['F']).astype(float)
    
    # simulate ppln response
    rs = smlt_ppln_ma(i_s, i_p, tau_rs, tau_as, x_ss, x_ps, DT)
        
    df_tr_nrl_ma[[f'R_{expt_id}' for expt_id in expt_ids]] = rs
        
    np.save(os.path.join(SAVE_DIR_MA, f'{SAVE_PFX_MA}_tr_{ctr}.npy'), np.array([{'df': df_tr_nrl_ma}]))

....................................................................................................................................................................................................................................................................................

# Only sine selectivity

In [ ]:
SAVE_DIR_MA = 'data/simple/mlv/ma_alt/baker_ma_sine_select'
SAVE_PFX_MA = 'mlv_baker_ma_sine_select'

if not os.path.exists(SAVE_DIR_MA):
    os.makedirs(SAVE_DIR_MA)

# neural response fits from Baker data
df_ma_param = pd.read_csv('data/simple/neur/baker_ma_fit_param.csv')
df_ma_param['X_P'] = 0

df_ma_param

In [ ]:
expt_ids = df_ma_param['EXPT_ID']

# get parameters
tau_rs = np.array(df_ma_param['TAU_R'])
tau_as = np.array(df_ma_param['TAU_A'])
x_ss = np.array(df_ma_param['X_S'])
x_ps = np.array(df_ma_param['X_P'])

In [8]:
# compute surrogate linear neural responses for each trial
for ctr, df_tr in enumerate(dfs_tr):
    df_tr_nrl_ma = df_tr.copy()
    sys.stdout.write('.')
    
    i_s = np.array(df_tr['S']).astype(float)
    i_p = np.array(df_tr['P'] | df_tr['F']).astype(float)
    
    # simulate ppln response
    rs = smlt_ppln_ma(i_s, i_p, tau_rs, tau_as, x_ss, x_ps, DT)
        
    df_tr_nrl_ma[[f'R_{expt_id}' for expt_id in expt_ids]] = rs
        
    np.save(os.path.join(SAVE_DIR_MA, f'{SAVE_PFX_MA}_tr_{ctr}.npy'), np.array([{'df': df_tr_nrl_ma}]))

....................................................................................................................................................................................................................................................................................

# Only pulse selectivity

In [6]:
SAVE_DIR_MA = 'data/simple/mlv/ma_alt/baker_ma_pulse_select'
SAVE_PFX_MA = 'mlv_baker_ma_pulse_select'

if not os.path.exists(SAVE_DIR_MA):
    os.makedirs(SAVE_DIR_MA)

# neural response fits from Baker data
df_ma_param = pd.read_csv('data/simple/neur/baker_ma_fit_param.csv')
df_ma_param['X_S'] = 0

df_ma_param

,EXPT_ID,LINE,FLY,ROI,ROI_USED,FIT_ERR,SUCCESS,T_0,R_0,TAU_R,TAU_A,X_S,X_P
0,0,R70G01,0,somas,False,0.275200,True,-0.000000,0.028882,6.202615,30.336758,0,-2.597432
1,1,R70G01,1,somas,False,0.186212,True,0.117647,0.025128,3.835468,21.821295,0,-1.472075
2,2,R70G01,2,somas,False,0.248414,True,-0.000000,0.055962,6.017162,15.058055,0,-2.095952
3,3,R70G01,3,somas,False,0.455963,True,-0.000000,-0.014227,6.016828,11.820576,0,-2.118245
4,4,R70G01,4,somas,False,0.229018,True,-0.000000,0.019831,6.434825,55.496220,0,-2.863647
...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,219,VT34811,0,somas,False,0.276087,True,-0.000000,0.039119,1.799608,1440.994269,0,2.494657
220,220,VT34811,0,ascending projection,False,0.037801,True,-0.000000,-0.001886,1.298841,27.643238,0,2.457383
221,221,vPN1_split,0,somas,False,0.404112,True,-0.588235,-0.014702,4.151226,6.155551,0,2.353217
222,222,vPN1_split,1,somas,False,1.205977,True,0.235294,-0.095665,5.924070,90.705238,0,0.604586
223,223,vPN1_split,2,somas,False,0.096240,True,-0.000000,-0.000413,3.664384,10.471628,0,1.021095

In [ ]:
expt_ids = df_ma_param['EXPT_ID']

# get parameters
tau_rs = np.array(df_ma_param['TAU_R'])
tau_as = np.array(df_ma_param['TAU_A'])
x_ss = np.array(df_ma_param['X_S'])
x_ps = np.array(df_ma_param['X_P'])

In [8]:
# compute surrogate linear neural responses for each trial
for ctr, df_tr in enumerate(dfs_tr):
    df_tr_nrl_ma = df_tr.copy()
    sys.stdout.write('.')
    
    i_s = np.array(df_tr['S']).astype(float)
    i_p = np.array(df_tr['P'] | df_tr['F']).astype(float)
    
    # simulate ppln response
    rs = smlt_ppln_ma(i_s, i_p, tau_rs, tau_as, x_ss, x_ps, DT)
        
    df_tr_nrl_ma[[f'R_{expt_id}' for expt_id in expt_ids]] = rs
        
    np.save(os.path.join(SAVE_DIR_MA, f'{SAVE_PFX_MA}_tr_{ctr}.npy'), np.array([{'df': df_tr_nrl_ma}]))

....................................................................................................................................................................................................................................................................................